# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: ci-tests
on:
  push:
    branches: [ branch-3.1-build-fixed ]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Cache for maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}-8-single
          restore-keys: |
            maven-repo-${{ hashFiles('**/pom.xml') }}-8
            maven-repo-${{ hashFiles('**/pom.xml') }}
            maven-repo-
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build with maven
        run: mvn clean install package -Dmaven.javadoc.skip=true -DskipTests -Pdist

  tests:
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Cache for maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}-8-single
          restore-keys: |
            maven-repo-${{ hashFiles('**/pom.xml') }}-8
            maven-repo-${{ hashFiles('**/pom.xml') }}
            maven-repo-
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Run tests with maven
        run: mvn test || true # Prevent workflow stop on test failure

  failures:
    needs:
      - tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get failed test classes
        run: |
          echo "Searching for failed tests in every module target directories..."
          find . -name surefire-reports -type d | while read dir; do
            grep -l -r "<failure" "$dir" | sed 's|.*/surefire-reports/||;s|.txt||;s|TEST-||;s|-|.|g' | while read class; do
              modulePath=$(dirname "$dir")
              moduleName=$(basename "$modulePath")
              echo "Module: $moduleName, Failed Test Class: $class"
            done
          done
